config/routes.rb
Rails.application.routes.draw do
  
    get 'backoffice', to: 'backoffice/dashboard#index'
    get 'admin', to: 'backoffice/dashboard#index'
    get 'filiais', to: 'backoffice/branches#index'
    get 'vendas', to: 'backoffice/sells#index'
    get 'parameters', to: 'backoffice/parameters#index'
    get 'panel', to: 'panel/dashboard#index'
    get 'cliente', to: 'panel/dashboard#index'
    get 'rescuepoints', to: 'backoffice/rescuepoints#index'
    get 'clientevendas', to: 'panel/reportseels#index'
    get 'indications', to: 'panel/indications#index'
    
  namespace :backoffice do
    resources :admins, except: [:show]
    resources :clients
    resources :branches
    resources :sells
    resources :parameters
    resources :rescuepoints
    get 'dashboard', to: 'dashboard#index'
    get 'clients', to: 'clients#index'
    get 'branches', to: 'branches#index'
    get 'sells', to: 'sells#index'
    get 'parameters', to: 'parameters#index'
    get 'rescuepoints', to: 'rescuepoints#index'
  end

  namespace :panel do
    resources :clients, except: [:show]
    resources :rescuepoints
    resources :reportsells
    resources :indications
    get 'dashboard', to: 'dashboard#index'
    get 'reportseels', to: 'reportsells#index'
    get 'search', to: 'reportsells#search'
    get 'indications', to: 'indications#index'
  end

  namespace :site do
    get 'home', to: 'home#index'
  end


  devise_for :clients, :skip => [:registrations]
  devise_for :admins, :skip => [:registrations]

  root 'site/home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/backoffice.rb
module Backoffice
  def self.table_name_prefix
    'backoffice_'
  end
end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
  before_action :set_admin, only: [:edit, :update, :destroy]

  def index
    @contador = Admin.all
  	@admins = Admin.order(:name).page(params[:page]).per(15)
    @branches = Branch.all
  end

  def new
    @admin = Admin.new
    options_for_select
  end

  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to backoffice_admins_path, notice: "A cadastro (#{@admin.email}) foi cadastrada com sucesso!"
    else
      render :new
    end
  end

  def edit
    options_for_select
    #usei o before_action para rodar a função set_admin
  end

  def destroy
    admin_email = @admin.email

    if @admin.destroy
      redirect_to backoffice_admins_path, notice: "A cadastro (#{admin_email}) foi excluido com sucesso!"
    else
      render :index
    end

  end

  def update
    passwd = params[:admin][:password]
    passwd_confirmation = params[:admin][:password_confirmation]
    if passwd.blank? && passwd_confirmation.blank?
      params[:admin].delete(:password)
      params[:admin].delete(:password_confirmation)
    end


    #usei o before_action para rodar a função set_admin
    if @admin.update(params_admin)
      redirect_to backoffice_admins_path, notice: "O cadastro (#{@admin.email}) foi atualizado com sucesso!"
    else
      render :edit
    end
  end

  private
    def options_for_select
      @branch_options_for_select = Branch.all
    end

    def set_admin
      @admin = Admin.find(params[:id])
    end

    def params_admin
      params.require(:admin).permit(:email, :password, :password_confirmation, :name, :cpf, :rg, :branch_id, :status)
    end


end

app/controllers/backoffice/branches_controller.rb
class Backoffice::BranchesController < BackofficeController
  before_action :set_branch, only: [:edit, :update, :destroy]

  def index
    @contador = Branch.all
    @admins = Admin.all
    @clients = Client.all
  	@branches = Branch.order(:name).page(params[:page]).per(15)
  end

  def new
    @branch = Branch.new

  end

  def create
  	@branch= Branch.new(params_branch)
    if @branch.save
      redirect_to backoffice_branches_path, notice: "A cadastro (#{@branch.name}) foi cadastrada com sucesso!"
    else
      render :new
    end
  end

  def edit
    #usei o before_action para rodar a função set_branch
  end

  def destroy
    branch_name = @branch.name

    if @branch.destroy
      redirect_to backoffice_branches_path, notice: "A cadastro (#{branch_name}) foi excluido com sucesso!"
    else
      render :index
    end

  end

  def update
    #usei o before_action para rodar a função set_branch
    if @branch.update(params_branch)
      redirect_to backoffice_branches_path, notice: "O cadastro (#{@branch.name}) foi atualizado com sucesso!"
    else
      render :edit
    end
  end

  private
    def set_branch
      @branch = Branch.find(params[:id])
    end

    def params_branch
      params.require(:branch).permit(:name, :city, :address, :neighbohod, :state, :status)
    end

end

app/controllers/backoffice/clients_controller.rb
class Backoffice::ClientsController < BackofficeController
  before_action :set_client, only: [:edit, :update, :destroy, :show]

  def index
    @contador = Client.where(:branch_id => current_admin.branch_id)
    @contativo = 0
    @continativo = 0
    @contador.each do |client|
      if client.status_br == "Ativo"
          @contativo = @contativo + 1
      elsif client.status_br == "Inativo"
          @continativo = @continativo + 1
      end
    end

    @indicateds = Client.order(:name).where("name like ? and status = ?", "%#{params[:term]}%", 0)
    
    respond_to do |format|
      format.html
      format.json {
        render json: @indicateds.map(&:name).to_json
      }
    end

  	@clients = Client.where(:branch_id => current_admin.branch_id).order(:name).page(params[:page]).per(15)
    @branches = Branch.all
  end

  def new
    @client = Client.new
    @client.build_bank

  end

  def create
    @client = Client.new(params_client)
    @client.branch_id = current_admin.branch_id
    
    if @client.save
      params_twig = {:father => @client.indicated, :child => @client.id, :level => 2, :status => 0, :created_at => Time.now, :updated_at => Time.now}
      @twig = Tree.new(params_twig)
      @twig.save
      params_twig2 = {:father => @client.id, :child => @client.id, :level => 1, :status => 0, :created_at => Time.now, :updated_at => Time.now}
      @twig2 = Tree.new(params_twig2)
      @twig2.save
      search = @client.indicated
      find_twig = Tree.where("child = ? AND father != ?",search,search)
      find_twig.each do |new_twig|
        new_level = new_twig.level+1
        if new_level>4
          new_twig_params = {:father => new_twig.father, :child => @client.id, :level => new_level,:status => 1, :created_at => Time.now, :updated_at => Time.now}
        else
          new_twig_params = {:father => new_twig.father, :child => @client.id, :level => new_level,:status => 0, :created_at => Time.now, :updated_at => Time.now}
        end
        create_twig = Tree.new(new_twig_params)
        create_twig.save
      end
      redirect_to backoffice_clients_path, notice: "O cadastro (#{@client.email}) foi cadastrada com sucesso!"
    else
      render :new
    end
  end

  def edit
    #usei o before_action para rodar a função set_client
  end

  def destroy
    client_email = @client.email

    if @client.destroy
      redirect_to backoffice_clients_path, notice: "O cadastro (#{client_email}) foi excluido com sucesso!"
    else
      render :index
    end

  end

  def update
    passwd = params[:client][:password]
    passwd_confirmation = params[:client][:password_confirmation]
    if passwd.blank? && passwd_confirmation.blank?
      params[:client].delete(:password)
      params[:client].delete(:password_confirmation)
    end


    #usei o before_action para rodar a função set_client
    if @client.update(params_client)
      redirect_to backoffice_clients_path, notice: "O cadastro (#{@client.email}) foi atualizado com sucesso!"
    else
      render :edit
    end
  end

  private
    def set_client
      @client = Client.find(params[:id])
    end

    def params_client
      params.require(:client).permit(:client_name, :email, :password, :password_confirmation,
                                     :name, :state, :cpf, :rg, :address, :neighbohod,
                                     :country, :status, :city, :postal_code, :complement,
                                     :birthdate, phones_attributes:[:phone,:_destroy,:id],
                                      bank_attributes:[:bank_name, :bank_account_type, :bank_agency,
                                     :bank_account, :bank_variance])
    end


end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController
  def index
    now = Time.now
    before_1_month = now -2419200
    if current_admin.id==2
      @clients = Client.where(:status => 0)
      @clients_last_month = Client.where(:status => 0, :created_at => before_1_month..now)
      @sells_last_month = Sell.where(:created_at => before_1_month..now)
      @rescued_last_month = Rescuepoint.where(:created_at => before_1_month..now)
    else
      @clients = Client.where(:status => 0, :branch_id => current_admin.branch_id )
      @clients_last_month = Client.where(:status => 0, :created_at => before_1_month..now, :branch_id => current_admin.branch_id)
      @sells_last_month = Sell.where(:created_at => before_1_month..now, :branch_id => current_admin.branch_id)
      @rescued_last_month = Rescuepoint.where(:created_at => before_1_month..now, :branch_id => current_admin.branch_id)
    end

    
  end
end

app/controllers/backoffice/parameters_controller.rb
class Backoffice::ParametersController < BackofficeController
  before_action :set_parameter, only: [:edit, :update, :destroy]

  def index
    @contador = Parameter.all
  	@parameters = Parameter.order(:label).page(params[:page]).per(15)
  end

  def new
    @parameter = Parameter.new

  end

  def create
    @parameter = Parameter.new(params_parameter)

    if @parameter.save
      redirect_to backoffice_parameters_path, notice: "O cadastro (#{@parameter.label}) foi cadastrada com sucesso!"
    else
      render :new
    end
  end

  def edit
    #usei o before_action para rodar a função set_parameter
  end

  def destroy

    if @parameter.destroy
      redirect_to backoffice_parameters_path, notice: "O cadastro (#{parameter_email}) foi excluido com sucesso!"
    else
      render :index
    end

  end

  def update
    
    if @parameter.update(params_params)
      redirect_to backoffice_parameters_path, notice: "O cadastro (#{@parameter.name}) foi atualizado com sucesso!"
    else
      render :edit
    end
  end

  private
  def set_parameter
    @parameter = Parameter.find(params[:id])
  end

  def params_params
    params.require(:parameter).permit(:name, :value)
  end

end

app/controllers/backoffice/rescuepoints_controller.rb
class Backoffice::RescuepointsController < BackofficeController
  before_action :set_rescuepoint, only: [:show, :edit, :update, :destroy]

  has_scope :search_client
  has_scope :search_created_at,:using => [:start_period, :end_period]
  has_scope :search_branch
  has_scope :active, :type => :boolean

  # GET /rescuepoints
  # GET /rescuepoints.json
  def index
    #@rescuepoints = Rescuepoint.order(:client_id).page(params[:page]).per(15)
    if current_admin.id==2
      @rescuepoints = apply_scopes(Rescuepoint).all
    else
      @rescuepoints = apply_scopes(Rescuepoint).all
    end
    @contador = @rescuepoints
    @branchs = Branch.all
    @clients = Client.all

    

  end

  # GET /rescuepoints/1
  # GET /rescuepoints/1.json
  def show
  end

  # GET /rescuepoints/new
  def new
    @rescuepoint = Rescuepoint.new
  end

  # GET /rescuepoints/1/edit
  def edit
  end

  # POST /rescuepoints
  # POST /rescuepoints.json
  def create
    @rescuepoint = Rescuepoint.new(rescuepoint_params)

    respond_to do |format|
      if @rescuepoint.save
        format.html { redirect_to @rescuepoint, notice: 'Rescuepoint was successfully created.' }
        format.json { render :show, status: :created, location: @rescuepoint }
      else
        format.html { render :new }
        format.json { render json: @rescuepoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rescuepoints/1
  # PATCH/PUT /rescuepoints/1.json
  def update
    respond_to do |format|
      
      if @rescuepoint.update({:rescued => 1})
        if rescuepoint_params[:voucher_id]!=""
          @voucher = Voucher.find(rescuepoint_params[:voucher_id])
          att_voucher = {:status => 1}
          if @voucher.update(att_voucher)
          end
        end
        format.html { redirect_to rescuepoints_url, notice: 'Rescuepoint was successfully updated.' }
        format.json { render :show, status: :ok, location: @rescuepoint }
      else
        format.html { render :edit }
        format.json { render json: @rescuepoint.errors, status: :unprocessable_entity }
      end
    end
  end

  

  # DELETE /rescuepoints/1
  # DELETE /rescuepoints/1.json
  def destroy
    @rescuepoint.destroy
    respond_to do |format|
      format.html { redirect_to rescuepoints_url, notice: 'Rescuepoint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rescuepoint
      @rescuepoint = Rescuepoint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rescuepoint_params
      #params.fetch(:rescuepoint, {})
      params.require(:rescuepoint).permit(:rescued, :voucher_id)
    end
end

app/controllers/backoffice/vouchers_controller.rb
class Backoffice::VouchersController < ApplicationController
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
	before_action :authenticate_admin!
  layout 'backoffice'
end

app/controllers/panel/rescuepoints_controller.rb
class Panel::RescuepointsController < PanelController
    before_action :set_client, only: [:edit, :update, :destroy]
    
    def index
        @rescuepoints = Rescuepoint.where(client_id: current_client.id).order(:client_id).page(params[:page]).per(15)
    end
       # GET /rescuepoints/1
    # GET /rescuepoints/1.json
    def show
        @dado = Rescuepoint.where(:client_id => current_client.id)
        @voucher = @dado.find(params[:id])
        respond_to do |format|
            format.html
            format.pdf do
                render pdf: "rescuepoints",
                layout: 'pdf'
            end
        end
    end

    # GET /rescuepoints/new
    def new
        @rescuepoint = Rescuepoint.new({client_id: current_client.id})
    end

    # GET /rescuepoints/1/edit
    def edit
    end

    # POST /rescuepoints
    # POST /rescuepoints.json
    def create
        @rescuepoint = Rescuepoint.new(rescuepoint_params)
        @rescuepoint.client_id = current_client.id
        @client = Client.find(current_client.id)
        if rescuepoint_params[:points].to_i <= @client.available_points
            respond_to do |format|
            att_client = {:available_points => @client.available_points - rescuepoint_params[:points].to_i}
            
            if @rescuepoint.save
                if @rescuepoint.rescuetype_id==2
                    @params_final = Parameter.where(:label => 'points_to_product')
                else
                    @params_final = Parameter.where(:label => 'points_to_money')
                end
                params_voucher = {:code => SecureRandom.hex(6),:value => @rescuepoint.points.to_i*@params_final[0].value.to_i, :status => 0, :rescuepoint_id => @rescuepoint.id}
                @voucher = Voucher.new(params_voucher)
                if @voucher.save
                    if @client.update(att_client)
                        format.html { redirect_to panel_rescuepoints_path, notice: 'Rescuepoint was successfully created.' }
                        format.json { render :show, status: :created, location: @rescuepoint }
                    end
                end
            else
                format.html { redirect_to :new_panel_rescuepoint_path }
                format.json { render json: @rescuepoint.errors, status: :unprocessable_entity }
            end
            end
        else
            redirect_to new_panel_rescuepoint_path, alert: "Você não tem (#{rescuepoint_params[:points]}) pontos para realizar esse saque."            
        end
    end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_rescuepoint
    @rescuepoint = Rescuepoint.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def rescuepoint_params
    #params.fetch(:rescuepoint, {})
    params.require(:rescuepoint).permit(:points, :rescuetype_id)
  end
end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
end

app/helpers/backoffice/branches_helper.rb
module Backoffice::BranchesHelper
end

app/helpers/backoffice/clients_helper.rb
module Backoffice::ClientsHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/backoffice/parameters_helper.rb
module Backoffice::ParametersHelper
end

app/helpers/backoffice/rescuepoints_helper.rb
module Backoffice::RescuepointsHelper
end

app/helpers/backoffice/sells_helper.rb
module Backoffice::SellsHelper
end

app/helpers/backoffice/vouchers_helper.rb
module Backoffice::VouchersHelper
end

app/views/backoffice/rescuepoints/edit.html.erb
<%= render partial: "backoffice/rescuepoints/shared/form", locals: {action: "Editando Cadastro"} %>

app/views/backoffice/rescuepoints/index.html.erb
<h1 class="page-header">Resgates</h1>

<div class="panel panel-default" >
    <div class="panel-heading">
        Opções
    </div>
    <!-- /.panel-heading -->

    <div class="panel-body">
        <div class="col-sm-12">
            <ul class="nav nav-pills nav-fill">
                <div class="col-sm-12">
                        <%= form_tag backoffice_rescuepoints_path, method: :get do %>
                        <div class="row">
                            <div class="col-sm-12 col-md-1">
                                <label>De:</label>
                            </div>
                            <div class="col-sm-12 col-md-2">
                                    <%= date_field_tag('search_created_at[start_period]', params[:start_period], class: "form-control datepicker")  %>
                            </div>
                            <div class="col-sm-12 col-md-1">
                                <label>até:</label>
                            </div>
                            <div class="col-sm-12 col-md-2">
                                    <%= date_field_tag('search_created_at[end_period]', params[:end_period], class: "form-control datepicker")  %>
                            </div>
                            <% if current_admin.id==2%>
                                <div class="col-sm-12 col-md-1">
                                        <label>Filial:</label>
                                    </div>
                                <div class="col-sm-12 col-md-2">
                                    <%= select_tag('search_branch',options_for_select(@branchs.map{|r| [r.name,r.id]}), {:include_blank => 'Todos', :class => "form-control"})  %>
                                </div>
                            <% end %>          
                        </div>
                        <div class="row">
                        </br>
                            <div class="col-md-1">
                                <label>Cliente:</label>
                            </div>
                            <div class="col-md-6">
                                <%= select_tag('search_client', options_for_select(@clients.map{|r| [r.name,r.id]}), {:include_blank => 'Todos', :class => "form-control"}) %>
                            </div>
                        </div>
                        <div class="row">
                                <%= hidden_field_tag('active', 0) %>
                                <%= submit_tag("Pesquisar", class: "btn btn-default") %>
                            <% end %>
                        </div>
                            
                </div>
            </ul>
        </div>
    </div>
    <!-- /.panel-body -->
</div>


<div class="panel panel-default" >
    <div class="panel-heading">
        Listando resgates <span class="badge badge-light"><%= @rescuepoints.count %></span>
       
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Cliente</th>
                        <th>Parâmetro</th>
                        <th>Pontos</th>
                        <th>Resgatado</th>
                        <th>Cód. Voucher</th>
                        <th>Status do Voucher</th>
                        <th colspan="2">Opções</th>
                    </tr>
                </thead>
                <tbody>
                    <% @rescuepoints.each do |rescues| %>
                        <tr>
                            <td width="3%"><%= rescues.id %></td>
                            <td><%= rescues.client.name %></td>
                            <td><%= rescues.rescuetype.label %></td>
                            <td><%= rescues.points %></td>
                            <td><%= rescues.rescued_br %></td>
                            <td><%= rescues.voucher.nil? ? 'Sem Voucher' : rescues.voucher.code  %></td>
                            <td><%= rescues.voucher.nil? ? 'Sem Voucher' : rescues.voucher.status  %></td>
                            
                            
                            <td>
                            <% if rescues.voucher and rescues.rescued=='no' %>
                                <% if rescues.voucher.status=="Liberado" %>
                                    <%= link_to edit_backoffice_rescuepoint_path(rescues.id), class: "btn btn-primary btn-circle" do %>
                                        <i class="fa fa-edit"></i>
                                    <% end %>
                                <% end %>
                            <% elsif rescues.rescued=="no" %>
                                <%= link_to edit_backoffice_rescuepoint_path(rescues.id), class: "btn btn-primary btn-circle" do %>
                                    <i class="fa fa-edit"></i>
                                <% end %>
                            <% end %>
                            </td>
                            
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
        </p> <center><%#= paginate @rescuepoints %></center>
    </div>
    <!-- /.panel-body -->
</div>