config/routes.rb
Rails.application.routes.draw do
  
    get 'backoffice', to: 'backoffice/dashboard#index'
    get 'admin', to: 'backoffice/dashboard#index'
    get 'filiais', to: 'backoffice/branches#index'
    get 'vendas', to: 'backoffice/sells#index'
    get 'parameters', to: 'backoffice/parameters#index'
    get 'panel', to: 'panel/dashboard#index'
    get 'cliente', to: 'panel/dashboard#index'
    get 'rescuepoints', to: 'backoffice/rescuepoints#index'
    get 'clientevendas', to: 'panel/reportseels#index'
    get 'indications', to: 'panel/indications#index'
    
  namespace :backoffice do
    resources :admins, except: [:show]
    resources :clients
    resources :branches
    resources :sells
    resources :parameters
    resources :rescuepoints
    get 'dashboard', to: 'dashboard#index'
    get 'clients', to: 'clients#index'
    get 'branches', to: 'branches#index'
    get 'sells', to: 'sells#index'
    get 'parameters', to: 'parameters#index'
    get 'rescuepoints', to: 'rescuepoints#index'
  end

  namespace :panel do
    resources :clients, except: [:show]
    resources :rescuepoints
    resources :reportsells
    resources :indications
    get 'dashboard', to: 'dashboard#index'
    get 'reportseels', to: 'reportsells#index'
    get 'search', to: 'reportsells#search'
    get 'indications', to: 'indications#index'
  end

  namespace :site do
    get 'home', to: 'home#index'
  end


  devise_for :clients, :skip => [:registrations]
  devise_for :admins, :skip => [:registrations]

  root 'site/home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sell.rb
class Sell < ApplicationRecord
  scope :search_client, -> client_id { where(:client_id => client_id)}
  scope :search_created_at, -> started_at, ended_at { where(:sell_date => started_at..ended_at) }
  scope :search_branch, -> branch_id { where(:branch_id => branch_id)}
  scope :active, -> {where(:status => 0)}
  
	enum status: {:active => 0, :inactive => 1}

	scope :with_active, -> {where(status: 0)}
	scope :with_inactive, -> {where(status: 1)}

  belongs_to :client
  belongs_to :branch, optional: true
 monetize :value_cents
  validates :value, numericality: { greater_than: -99999999999999999 }
 #Validates

attr_accessor  :value_venda

 validates :client_id, :code, :sell_date, presence: true

def client_name
  client.try(:name, :id)
end

def client_name=(name)
  self.client = Client.find_by(name: name) if name.present?
end

end

app/controllers/backoffice/sells_controller.rb
class Backoffice::SellsController < BackofficeController
  before_action :set_sell, only: [:edit, :update, :destroy]
  has_scope :search_client
  has_scope :search_created_at,:using => [:start_period, :end_period]
  has_scope :search_branch
  has_scope :active, :type => :boolean
  def index
    if current_admin.id==2
      @sells = apply_scopes(Sell).all
    else
      @sells = apply_scopes(Sell).all
    end
    @contador = @sells    
    @branchs = Branch.all
    @clients = Client.all

    respond_to do |format|
      format.html
      format.json {
        render json: @clients.map(&:name).to_json
      }
    end

  end


  def new
    @sell = Sell.new
    options_for_select
  end

  def create

    @sell = Sell.new(params_sell)
    @sell.branch_id = current_admin.branch_id
    if params_sell[:sell_type] == "formdev"
      @sell.value = @sell.value * -1
    elsif params_sell[:sell_type] == "formvendasdev"
      @sell.value =params_sell[:value_venda]
    else
      @sell.value = @sell.value
    end


    if @sell.save
      if @sell.value>0 # só salva os pontos se for venda
        #salvar pontos da compra para o cliente que realizou a compra
        twig = Tree.where("father = ? and child = ? and status = 0", @sell.client_id,@sell.client_id) #pega o id da tree do cliente para os pontos dele mesmo
        level_value = Parameter.where(:label => "value_nivel_1", :status => 0)[0].value #pega o valor do nivel 1
        calculate_points = (@sell.value.fractional*level_value.to_f/100)/100 # calcula o valor em pontos
        new_points_param = {:tree_id => twig[0].id, :sell_id => @sell.id, :points => calculate_points, :status => 0, :created_at => Time.now, :updated_at => Time.now}
        add_points = Point.new(new_points_param) #cria novo Point com os paramêtros
        add_points.save # salva ¬¬
        # atualizar pontos do cliente
        client_father = Client.find(@sell.client_id)
        points_client = client_father.total_points.to_i+calculate_points
        available_points_client = client_father.available_points.to_i+calculate_points
        update_client = {:total_points => points_client, :available_points => available_points_client}
        client_father.update(update_client)
        # salvar pontos da compra para os niveis superiores do cliente que realizou a compra
        twigs = Tree.where("child = ? and status = 0 and father != ?", @sell.client_id,@sell.client_id) # pega todas as trees que contem o cliente como filho
        twigs.each do |new_twig| # loop pelas tree
          level_value = Parameter.where(:label => "value_nivel_"+new_twig.level.to_s, :status => 0)[0].value #pega o paramentro baseado no level da tree
          calculate_points = (@sell.value.fractional*level_value.to_f/100)/100 #calcular pontos
          new_points_param = {:tree_id => new_twig.id, :sell_id => @sell.id, :points => calculate_points, :status => 0, :created_at => Time.now, :updated_at => Time.now }
          add_points = Point.new(new_points_param) #cria novo Point com os paramêtros
          add_points.save # salva ¬¬
          #atualizar pontos do cliente pai
          client_father = Client.find(new_twig.father) # pega o cliente pai
          points_client = client_father.total_points.to_i+calculate_points
          available_points_client = client_father.available_points.to_i+calculate_points
          update_client = {:total_points => points_client, :available_points => available_points_client}
          client_father.update(update_client) #atualizando cliente pai
        end
      end
      if params_sell[:sell_type] == "formvendasdev"
        @sell2 = Sell.new(params_sell)
        @sell2.value = @sell2.value * -1
        @sell2.branch_id = current_admin.branch_id
    
        @sell2.created_at = Date.current
        if @sell2.save
          redirect_to backoffice_sells_path, notice: "A cadastro (#{@sell.code}) foi cadastrada com sucesso!"
        end
      else
        redirect_to backoffice_sells_path, notice: "A cadastro (#{@sell.code}) foi cadastrada com sucesso!"
      end
    else
      render :index
    end
  end

  def edit
    options_for_select
    #usei o before_action para rodar a função set_sell
  end

  def destroy
    sell_code = @sell.code

    if @sell.destroy
      redirect_to backoffice_sells_path, notice: "A cadastro (#{sell_code}) foi excluido com sucesso!"
    else
      render :index
    end

  end

  def update
    #usei o before_action para rodar a função set_sell
    if @sell.update(params_sell)
      redirect_to backoffice_sells_path, notice: "O cadastro (#{@sell.code}) foi atualizado com sucesso!"
    else
      render :edit
    end
  end

  private
    def options_for_select
      @client_options_for_select = Client.all
    end

    def set_sell
      @sell = Sell.find(params[:id])
    end

    def params_sell
      params.require(:sell).permit(:client_name, :sell_type, :value, :code, :description, :sell_date, :value_venda, :status)
    end


end

app/helpers/backoffice/sells_helper.rb
module Backoffice::SellsHelper
end

app/views/backoffice/sells/shared/_form_edit.html.erb
<h1 class="page-header">Vendas</h1>
<% if @sell.errors.any? %>
  <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <!-- message -->
    <ul>
      <% @sell.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>

  </div>
<% end %>
<div class="panel panel-default" >
    <div class="panel-heading">
        <%= action %>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="col-lg-6">
            <%= form_for([:backoffice, @sell]) do |f| %>
            <div class="form-group">
                <label>Cliente</label><br />
                <%= @sell.client.name %>
            </div>
            <div class="form-group">
                <label>Data da venda</label>
                <%= f.text_field :sell_date, class: "form-control datepicker", value: (l(@sell.sell_date) unless @sell.sell_date.blank?) %>
            </div>
            <div class="form-group">
                <label>Valor da venda</label>
                <%= f.text_field :value, class: "form-control", placeholder: "Ex.: 1350,15" %>
            </div>
            <div class="form-group">
                <label>Código</label>
                <%= f.text_field :code, class:"form-control", placeholder:"Código da venda" %>
            </div>
            <div class="form-group">
                <label>Descrição</label>
                <%= f.text_area :description, class:"form-control", placeholder:"Descrição da venda" %>
            </div>
            <button type="submit" class="btn btn-default">Cadastrar</button>
            <% end %>
        </div>
    </div>
    <!-- /.panel-body -->
</div>
<!-- /panel panel-default -->

app/views/backoffice/sells/shared/_form_new.html.erb
<h1 class="page-header">Vendas / Devoluções</h1>
<% if @sell.errors.any? %>
  <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <!-- message -->
    <ul>
      <% @sell.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>

  </div>
<% end %>

<!-- Painel de opções -->
<div class="panel panel-default" >
    <div class="panel-heading">
        Opções
    </div>
    <!-- /.panel-heading -->

    <div class="panel-body">
        <div class="col-sm-9">
            <ul class="nav nav-pills nav-fill">
                <div class="col-4 col-sm-3">
                    <div class="input-group mb-2 mb-sm-0">
                        <div class="input-group-addon">Vendas</div>
                        <li class="nav-item">
                             <input id="checkbox1" type="checkbox" checked data-toggle="toggle" data-on="Ativado" data-off="Desativado">
                        </li>
                    </div>
                    <div id="status1"></div>
                </div>
                <div class="col-4 col-sm-3">
                    <div class="input-group mb-2 mb-sm-0">
                        <div class="input-group-addon">Devoluções</div>
                        <li class="nav-item">
                             <input id="checkbox2" type="checkbox" checked data-toggle="toggle" data-on="Ativado" data-off="Desativado">
                        </li>
                    </div>
                    <div id="status2"></div>
                </div>
                <div class="col-4 col-sm-3">
                    <div class="input-group mb-2 mb-sm-0">
                        <div class="input-group-addon">Vendas e Devoluções</div>
                        <li class="nav-item">
                             <input id="checkbox3" type="checkbox" checked data-toggle="toggle" data-on="Ativado" data-off="Desativado">
                        </li>
                    </div>
                    <div id="status3"></div>
                </div>
            </ul>
        </div>
    </div>
    <!-- /.panel-body -->
</div>
<!-- /panel panel-default -->


<!-- VENDAS -->
<div class="panel panel-default" id="formvendas">
    <div class="panel-heading">
        Vendas
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="col-lg-6">
            <%= form_for([:backoffice, @sell]) do |f| %>
            <div class="form-group">
                <label>Cliente</label>
                <%= f.text_field :client_name, class: "form-control sell_client_name", data: { autocomplete_source: backoffice_clients_path} %>
            </div>
            <div class="form-group">
                <label>Data da venda</label>
                <%= f.text_field :sell_date, class: "form-control", id: "datepicker1", value: l(Date.today) %>
            </div>
            <div class="form-group">
                <label>Valor da venda</label>
                <%= f.text_field :value, class: "form-control", placeholder: "Ex.: 1350,15" %>
            </div>
            <div class="form-group">
                <label>Nota fiscal</label>
                <%= f.text_field :code, class:"form-control", placeholder:"Nota fiscal da venda" %>
            </div>
            <div class="form-group">
                <label>Descrição</label>
                <%= f.text_area :description, class:"form-control", placeholder:"Descrição da venda", size: "60x12" %>
            </div>
            <%= f.hidden_field(:sell_type, value: "formvendas") %>
            <%= f.hidden_field(:status, value: "active") %>
            <button type="submit" class="btn btn-default">Cadastrar</button>
            <% end %>
        </div>
    </div>
    <!-- /.panel-body -->
</div>
<!-- /panel panel-default -->

<!-- DEVOLUÇÕESa -->
<div class="panel panel-default" id="formdev">
    <div class="panel-heading">
        Devoluções
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="col-lg-6">
            <%= form_for([:backoffice, @sell]) do |f| %>
            <div class="form-group">
                <label>Cliente</label>
                <%= f.text_field :client_name, class: "form-control sell_client_name", data: { autocomplete_source: backoffice_sells_path} %>
            </div>
            <div class="form-group">
                <label>Data da venda</label>
                <%= f.text_field :sell_date, class: "form-control", id: "datepicker2", value: l(Date.today) %>
            </div>
            <div class="form-group">
                <label>Valor da venda</label>
                <%= f.text_field :value, class: "form-control", placeholder: "Ex.: 1350,15" %>
            </div>
            <div class="form-group">
                <label>Nota fiscal</label>
                <%= f.text_field :code, class:"form-control", placeholder:"Nota fiscal da venda" %>
            </div>
            <div class="form-group">
                <label>Descrição</label>
                <%= f.text_area :description, class:"form-control", placeholder:"Descrição da venda", size: "60x12" %>
            </div>
            <%= f.hidden_field(:sell_type, value: "formdev") %>
            <%= f.hidden_field(:status, value: "active") %>
            <button type="submit" class="btn btn-default">Cadastrar</button>
            <% end %>
        </div>
    </div>
    <!-- /.panel-body -->
</div>
<!-- /panel panel-default -->


<!-- VENDAS E DEVOLUÇÕES -->
<div class="panel panel-default" id="formvendasdev">
    <div class="panel-heading">
        Vendas e Devoluções
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="col-lg-6">
            <%= form_for([:backoffice, @sell]) do |f| %>
            <div class="form-group" >
                <label>Cliente</label>
                <%= f.text_field :client_name, class: "form-control sell_client_name", data: { autocomplete_source: backoffice_sells_path} %>
            </div>
            <div class="form-group">
                <label>Data da venda</label>
                <%= f.text_field :sell_date, class: "form-control", id: "datepicker3", value: l(Date.today) %>
            </div>
            <div class="form-group">
                <label>Valor da venda</label>
                <%= f.text_field :value_venda, class: "form-control", placeholder: "Ex.: 1350,15" %>
            </div>
            <div class="form-group">
                <label>Valor da devolução</label>
                <%= f.text_field :value, class: "form-control", placeholder: "Ex.: 3218,15" %>
            </div>
            <div class="form-group">
                <label>Nota fiscal</label>
                <%= f.text_field :code, class:"form-control", placeholder:"Nota fiscal da venda" %>
            </div>
            <div class="form-group">
                <label>Descrição</label>
                <%= f.text_area :description, class:"form-control", placeholder:"Descrição da venda", size: "60x12" %>
            </div>
            <%= f.hidden_field(:sell_type, value: "formvendasdev") %>
            <%= f.hidden_field(:status, value: "active") %>
            <button type="submit" class="btn btn-default">Cadastrar</button>
            <% end %>
        </div>
    </div>
    <!-- /.panel-body -->
</div>
<!-- /panel panel-default -->


