config/routes.rb
Rails.application.routes.draw do
  
    get 'backoffice', to: 'backoffice/dashboard#index'
    get 'admin', to: 'backoffice/dashboard#index'
    get 'filiais', to: 'backoffice/branches#index'
    get 'vendas', to: 'backoffice/sells#index'
    get 'parameters', to: 'backoffice/parameters#index'
    get 'panel', to: 'panel/dashboard#index'
    get 'cliente', to: 'panel/dashboard#index'
    get 'rescuepoints', to: 'backoffice/rescuepoints#index'
    get 'clientevendas', to: 'panel/reportseels#index'
    get 'indications', to: 'panel/indications#index'
    
  namespace :backoffice do
    resources :admins, except: [:show]
    resources :clients
    resources :branches
    resources :sells
    resources :parameters
    resources :rescuepoints
    get 'dashboard', to: 'dashboard#index'
    get 'clients', to: 'clients#index'
    get 'branches', to: 'branches#index'
    get 'sells', to: 'sells#index'
    get 'parameters', to: 'parameters#index'
    get 'rescuepoints', to: 'rescuepoints#index'
  end

  namespace :panel do
    resources :clients, except: [:show]
    resources :rescuepoints
    resources :reportsells
    resources :indications
    get 'dashboard', to: 'dashboard#index'
    get 'reportseels', to: 'reportsells#index'
    get 'search', to: 'reportsells#search'
    get 'indications', to: 'indications#index'
  end

  namespace :site do
    get 'home', to: 'home#index'
  end


  devise_for :clients, :skip => [:registrations]
  devise_for :admins, :skip => [:registrations]

  root 'site/home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
	enum status: {:active => 0, :inactive => 1}

  scope :with_active, -> {where(status: 0)}
  scope :with_inactive, -> {where(status: 1)}


	belongs_to :branch

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def status_br
  if self.status == 'active'
		'Ativo'
	else
		'Inativo'
	end
  end
  def rescued_br
    if self.rescued == 'yes'
      'Resgatado'
    else
      'Aguardando'
    end
  end
  def sell_type_br
    if self.value_cents > 0
      "Venda"
    else
      "Devolução"
    end
  end
end

app/models/backoffice.rb
module Backoffice
  def self.table_name_prefix
    'backoffice_'
  end
end

app/models/bank.rb
class Bank < ApplicationRecord
	has_one :client
end

app/models/branch.rb
class Branch < ApplicationRecord
  enum status: {:active => 0, :inactive => 1}

  scope :with_active, -> {where(status: 0)}
  scope :with_inactive, -> {where(status: 1)}

  has_many :clients
  has_many :admins
  has_many :sells
  has_many :recuepoint
end

app/models/client.rb
class Client < ApplicationRecord
	enum status: {:active => 0, :inactive => 1}

	scope :with_active, -> {where(status: 0)}
	scope :with_inactive, -> {where(status: 1)}

	has_many :phones
	belongs_to :branch
	has_many :sells
	belongs_to :bank
	belongs_to :client, foreign_key: "indicated", optional: true
	
	#validates :cpf, :rg, uniqueness: true

	def client_name
		indicated.try(:name, :id)
	end
	  
	def client_name=(name)
		self.indicated = Client.find_by(name: name).id if name.present?
		
	end

	accepts_nested_attributes_for :phones, :bank, allow_destroy: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/parameter.rb
class Parameter < ApplicationRecord
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :client
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :tree
  belongs_to :sell
end

app/models/rescuepoint.rb
class Rescuepoint < ApplicationRecord


  scope :search_client, -> client_id { where(:client_id => client_id)}
  scope :search_created_at, -> started_at, ended_at { where(:rescue_date => started_at..ended_at) }
  scope :search_branch, -> branch_id { where(:branch_id => branch_id)}
  scope :active, -> {where(:status => 0)}



  enum rescued: {:no => 0, :yes => 1}
  
    scope :with_rescued, -> {where(rescued: 1)}
    scope :with_no_rescued, -> {where(rescued: 0)}
  belongs_to :client
  belongs_to :rescuetype
  belongs_to :branch
  has_one :voucher
  attr_accessor  :value_venda


end

app/models/rescuetype.rb
class Rescuetype < ApplicationRecord
end

app/models/sell.rb
class Sell < ApplicationRecord
  scope :search_client, -> client_id { where(:client_id => client_id)}
  scope :search_created_at, -> started_at, ended_at { where(:sell_date => started_at..ended_at) }
  scope :search_branch, -> branch_id { where(:branch_id => branch_id)}
  scope :active, -> {where(:status => 0)}
  
	enum status: {:active => 0, :inactive => 1}

	scope :with_active, -> {where(status: 0)}
	scope :with_inactive, -> {where(status: 1)}

  belongs_to :client
  belongs_to :branch, optional: true
 monetize :value_cents
  validates :value, numericality: { greater_than: -99999999999999999 }
 #Validates

attr_accessor  :value_venda

 validates :client_id, :code, :sell_date, presence: true

def client_name
  client.try(:name, :id)
end

def client_name=(name)
  self.client = Client.find_by(name: name) if name.present?
end

end

app/models/tree.rb
class Tree < ApplicationRecord
    belongs_to :client_father, foreign_key: "father", class_name: 'Client' 
    belongs_to :client_child, foreign_key: "child", class_name: 'Client'
    has_many :point
end

app/models/voucher.rb
class Voucher < ApplicationRecord
  enum status: {:'Liberado/Aguardando Pagamento' => 0, :'Usado/Pagamento Realizado' => 1}
  scope :with_rescued, -> {where(status: 1)}
  scope :with_no_rescued, -> {where(status: 0)}  
  belongs_to :rescuepoint
  validates :code, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  layout :layout_by_resource

  private

  def layout_by_resource
	  if devise_controller? && resource_name == :admin
	    "backoffice_devise"
	  elsif
	   devise_controller? && resource_name == :client
	  		"panel_devise"
	  else
	    "application"
	  end
	end

end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
	before_action :authenticate_admin!
  layout 'backoffice'
end

app/controllers/panel_controller.rb
class PanelController < ApplicationController
	before_action :authenticate_client!
  layout 'panel'
end

app/helpers/application_helper.rb
module ApplicationHelper

	ESTADOS_BRASILEIROS = [
    ["Acre", "AC"],
    ["Alagoas", "AL"],
    ["Amapá", "AP"],
    ["Amazonas", "AM"],
    ["Bahia", "BA"],
    ["Ceará", "CE"],
    ["Distrito Federal", "DF"],
    ["Espírito Santo", "ES"],
    ["Goiás", "GO"],
    ["Maranhão", "MA"],
    ["Mato Grosso", "MT"],
    ["Mato Grosso do Sul", "MS"],
    ["Minas Gerais", "MG"],
    ["Pará", "PA"],
    ["Paraíba", "PB"],
    ["Paraná", "PR"],
    ["Pernambuco", "PE"],
    ["Piauí", "PI"],
    ["Rio de Janeiro", "RJ"],
    ["Rio Grande do Norte", "RN"],
    ["Rio Grande do Sul", "RS"],
    ["Rondônia", "RO"],
    ["Roraima", "RR"],
    ["Santa Catarina", "SC"],
    ["São Paulo", "SP"],
    ["Sergipe", "SE"],
    ["Tocantins", "TO"]
  ]

    STATUS = [
    ["Ativo", "active"],
    ["Inativo", "inactive"]
    ]

    TIPOSCONTAS = [
    ["Conta Corrente", "Conta Corrente"],
    ["Poupança", "Poupança"]
    ]
    
    RESCUED = [
      ["Dinheiro" ,"1"],
      ["Produtos","2"]
    ]

  def options_for_states(selected)
    options_for_select(ESTADOS_BRASILEIROS, selected)
  end

  def options_for_status(selected)
    options_for_select(STATUS, selected)
  end

  def options_for_acc_type(selected)
    options_for_select(TIPOSCONTAS, selected)
  end

  def options_for_rescue(selected)
    options_for_select(RESCUED,selected)
  end


end

app/helpers/panel/clients_helper.rb
module Panel::ClientsHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/views/backoffice/admins/shared/_form.html.erb
<h1 class="page-header">Administradores</h1>
<% if @admin.errors.any? %>
  <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <!-- message -->
    <ul>
      <% @admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>

  </div>
<% end %>
<div class="panel panel-default" >
    <div class="panel-heading">
        <%= action %>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="col-lg-6">
            <%= form_for([:backoffice, @admin]) do |f| %>
            <div class="form-group">
                <label>Email</label>
                <%= f.text_field :email, class:"form-control", placeholder:"Email do administrador" %>
            </div>
            <div class="form-group">
                <label>Senha</label>
                <%= f.password_field :password, class:"form-control", placeholder:"Senha" %>
            </div>
            <div class="form-group">
                <label>Confirmação da Senha</label>
                <%= f.password_field :password_confirmation, class:"form-control", placeholder:"Confirmação da Senha" %>
            </div>
            <div class="form-group">
                <label>Nome</label>
                <%= f.text_field :name, class:"form-control", placeholder:"Nome" %>
            </div>
            <div class="form-group">
                <label>CPF</label>
                <%= f.text_field :cpf, class:"form-control", placeholder:"CPF", onkeyup:"mascara('###.###.###-##',this,event)" %>
            </div>
            <div class="form-group">
                <label>RG</label>
                <%= f.text_field :rg, class:"form-control", placeholder:"RG", onkeyup:"mascara('##.###.###-#',this,event)" %>
            </div>
            <div class="form-group">
                <label>Status</label>
                <% if current_admin.id != @admin.id %>
                    <%= f.select :status, options_for_status(@admin.status), {}, {:class =>"form-control"} %>
                <% else %>
                    <br />Ativo
                <% end %>
            </div>
            <div class="form-group">
                <label>Filial</label>
                <%= f.collection_select(:branch_id, @branch_options_for_select, :id, :name, {}, {:class =>"form-control"}) %>
            </div>
            <button type="submit" class="btn btn-default">Cadastrar</button>
            <% end %>
        </div>
    </div>
    <!-- /.panel-body -->
</div>
<!-- /panel panel-default -->

app/views/layouts/shared/_notifications.html.erb
<% if notice %>
  <%= javascript_tag "$.notify( { message: '#{notice}'}, { type: 'success', placement: { from: 'top', align: 'center' }});" %>
<% end %>

<% if alert %>
    <%= javascript_tag "$.notify( { message: '#{alert}'}, { type: 'danger', placement: { from: 'top', align: 'center' }});" %>
<% end %>